name: On Push

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: make setup
      - name: run_tests
        run: make tests
      - name: run_lint
        run: make lint
